[package]
name = "oxocarbon"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
nvim-oxi = {version = "0.2.1" }


[features]
"neovim-0-7" = ["nvim-oxi/neovim-0-7"]
"neovim-0-8" = ["nvim-oxi/neovim-0-8"]
"neovim-nightly" = ["nvim-oxi/neovim-nightly"]
